name: Test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build
      - name: Run prettier
        run: yarn prettier-check
      - name: Run eslint
        run: yarn eslint
      - name: Run tests
        run: yarn test
